# Generated by Django 6.1 on 2026-08-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="IT", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
            preserve_default=False,
        ),
    ]
