# Generated by Django 6.1 on 2026-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_app", "0002_employee_department_employee_salary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("grade", models.CharField(max_length=3)),
            ],
        ),
    ]
